services:
  mysql:
    image: 'mysql:latest'
    container_name: 'splearn-mysql'
    environment:
      - 'MYSQL_DATABASE=splearn'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=spring'
    ports:
      - '3306:3306'
